### ISSUE TITLE
Does Halcyon support link arrays

### ISSUE THREAD

**Issue by NiklasArbin** [visualeyes/halcyon#12]
Does Halcyon support links as arrays such as:

` "_links": {
        "self": { "href": "/orders" },
        "curies": [{ "name": "ea", "href": "http://example.com/docs/rels/{rel}", "templated": true }],
        "next": { "href": "/orders?page=2" },
        "ea:find": {
            "href": "/orders{?id}",
            "templated": true
        },
        "ea:admin": [{
            "href": "/admins/2",
            "title": "Fred"
        }, {
            "href": "/admins/5",
            "title": "Kate"
        }]
    },}`

**Comment by johncmckim** [comment]
It does support link arrays. However, I found that there was a bug with that I have fixed in [this commit](https://github.com/visualeyes/halcyon/commit/f969b091ed05c1d7164ea95d91e7b9464217d75f) and released in [1.1.54-alpha](https://www.nuget.org/packages/Halcyon/1.1.54-alpha).

For this to work, just add links as normally and links with the same `rel` will be grouped into a link array. 

Let me know if you have any issues with it.

**Comment by NiklasArbin** [comment]
Great, looking into the test cases it seems that there is a fluent API for building the HAL response that is a lot more appealing than the current IHttpController extension. Is this something added in 1.1.54-alpha as well?

**Comment by johncmckim** [comment]
That's always been there. The [controller extensions](https://github.com/visualeyes/halcyon/blob/master/src/Halcyon.Mvc/HAL/ControllerExtensions.cs) just help create the response.

You should be able to use the response as below:

```c#
var response = new HALResponse(model, new HALModelConfig {
                      LinkBase = Url.Content("~/api") // base your links off this location
                  }) // config is optional
                 .AddLinks(linkOne)
                 .AddLinks(linkTwo)
                 .AddEmbeddedCollection(embeddedName, embedded);

return this.Ok(response);
```

I'll create an issue to document using this method over the extension methods. In my opinion, the extension methods are good because they're easy, but this give you more control.

**Comment by NiklasArbin** [comment]
Thanks, I was underway rolling my own HAL writer just beacuse of the extension methods imo readability and link collections issure. Are you open for future pull requests? We now have two large projects for different companiers that I know of that will base their HAL on Halcyon.

**Comment by johncmckim** [comment]
Very open to pull requests, just give us a heads up first so the issues can be discussed.

The reasons I made Halcyon are [discussed here](https://medium.com/@johncmckim/halcyon-hal-for-net-ebc416844152#.938kpdcrc). The two core ideas being:

> * I needed to be able to return HAL or plain JSON based on the accept header. The client should be able to chose whether or not to use HAL.
> * I don’t want to significantly modify Models to return HAL formatted JSON

As long as the project keeps to those ideals, I am fine changes and improvements.

**Comment by johncmckim** [comment]
I'm closing this now, but again, let me know if you have any more questions.
