### ISSUE TITLE
HALModel Doesn't Preserve Serialization Attributes

### ISSUE THREAD

**Issue by IsaacSanch** [visualeyes/halcyon#3]
One issue I have found with using this approach is that it doesn't obey the serialization attributes of the backing object. For example, `JsonIgnore` attributes are not passed through.

**Comment by johncmckim** [comment]
That's a very good point. My goal is to void littering models with HAL specific properties, hence the dynamic approach.

As you may have found, code converts the model into a Dictionary and then adds the _links properties to it. While it would be very easy to implement, JsonIgnore and JsonProperties, it's not a really good long term solution.

That doesn't mean keeping with the original goal is impossible. I am going to look into using [Dynamic Proxies](http://www.castleproject.org/projects/dynamicproxy/) instead of converting the object to a dictionary. It looks like this would allow _links to be dynamically added and keep the attributes.

I'll let you know what I find.

**Comment by IsaacSanch** [comment]
I ended up doing a rewrite of the HALModel class to get it all working.

I diteched the dictionary and keep the backing object as a property instead. From there I modified the serialization process to be handled by a JsonConverter that creates an internal representation of the original object and amends the links and embeds onto it. This should work for any custom serialization attributes. The current "meh" about the changes is that it (currently) no longer uses DynamicObject, so properties can't be set after creating the representation. I may end up going back to that, but not sure if it has any strong advantage to doing so.

I also made a modification so that the links are resolved at serialization and it runs the parameters through the serializer to get their values. (In my use case I need to use Guids and wanted them modified into a Base64 URI-friendly representation.) 

I haven't made this method handle Deserialization yet. Not sure if its necessary.

[Changes in fork](https://github.com/IsaacSanch/halcyon/commit/77f795684d91aa166a4918c232af05cf96e892df)

**Comment by johncmckim** [comment]
@IsaacSanch  I wan't planning on supporting Deserialization. If it's required, that can happen later.

There are some pretty significant design changes here. 

Am I correct in saying that this will always return models in HAL format? One important feature of the package is the ability to return plain JSON and HAL formatted JSON. This gives API client's the ability to choose whether to use HAL or not.

You have also removed all the controller extensions. This changes the usage from:
````
return this.HAL(fooModel, new Link[] {
      new Link("self", "/api/foo/{id}"),
      new Link("foo:bar", "/api/foo/{id}/bar")
});
```` 
to this:
````
var halModel = new HALModel(model);
halModel.AddLinks(new Link[] {
      new Link("self", "/api/foo/{id}"),
      new Link("foo:bar", "/api/foo/{id}/bar")
});
return this.Ok(halModel);
````

Is there a reason you have done this? I would much rather see the Extension methods kept in place. I don't really want the user to have to think too much about HALModels. I want them to be able to return their existing models + links via an easy method.

As a general note, if you're planning on sending a pull request, can you make sure the formatting matches the existing style?

**Comment by IsaacSanch** [comment]
@johncmckim The design changes were just me working to get the features I needed. I'm not sold to any changes as far as pulling them back to the main project. I've re-added the controller extensions now that I've had time this morning to fix their internal calls. (That's why I pulled them.)

Each of the controller extensions is now wired up.

For when more explicit control is needed I've tweaked the available calls so that using chaining it would look like this:
```
            return new HALModel(model)
                .AddLinks(modelLinks)
                .AddEmbeddedCollection(embeddedName, embeddedModel, embeddedLinks)
                .ToResult(controller, relativeLinkBase);
```

**Comment by IsaacSanch** [comment]
Forgot to mention. I'm planning to implement the ability to return plain objects.... Planning to put some time into that soon.

**Comment by johncmckim** [comment]
@IsaacSanch Great. I look forward to seeing what you come up with.

**Comment by IsaacSanch** [comment]
Content negotiation is fixed in the latest commit to the fork. Still looking at re-adding DynamicObject abilities.

**Comment by IsaacSanch** [comment]
@johncmckim Status update...

Within the fork I've made some additional design changes that have made things a little more robust.

- No longer taking over responsibility for `application/json` requests. Instead, the HALModel type has a JsonConverter assigned that resolves for all requests passed through the default handler (JsonMediaTypeFormatter.) This is a breaking change, as the JsonMediaTypeFormatter will need to no longer be removed from the pipeline when the HalMediaTypeFormatter is added. However, I believe that this approach is advantageous as it allows for agnostic handling of data types returned from the API controller.

- Added attributes which can be attached to DTO classes to intelligently create the HAL structure.
```
    [HalModel("~/api/")]
    public class OrderDto
    {
        [HalLink("self", "orders/{value}")]
        public Guid Id { get; set; }

        [HalLink("users", "users/{value}")]
        public Guid UserId { get; set; }

        [HalEmbeddedValues()]
        public dynamic[] Items { get; set; }

        public DateTime MadeDate { get; set; }

        public DateTime FulfilledDate { get; set; }
    }
```
```
        [HttpGet, Route("orders/{Id:guid}")]
        public dynamic GetOrder(Guid Id)
        {
            return new OrderDto(...);
        }
```

If the design changes are too far removed from your own vision of how you want to produce HAL, let me know... I'm willing to make this a permanent fork and rename it.

**Comment by johncmckim** [comment]
@IsaacSanch I'll have a look at it soon. I'm not against changing the API design, but it has to stick with the original intentions.

**Comment by johncmckim** [comment]
@IsaacSanch I pulled your code into a branch on my dev machine to look at it. However, the project doesn't appear to build? It looks like none of the tests have been updated to reflect the changes you made.

As you said, there are lot of big changes here. I am concerned about the level of complexity added to the code, especially since there appears to be no tests for that code. My goal for this project is to keep it simple.

There are some ideas I like i.e. the ToResult extension method. I also think that removing the dynamic model and using JObject to construct the JSON is probably a good idea.

The attributes support is interesting. However, does this change remove support for objects without attributes?

There are some other things I am concerned about
* GetFlattenedModelList - does this only serialize embedded models?
* Expand request parameter in the Media type formatter? What does this do? Does it change the response based on the query string?

Right now I am not inclined to pull in your changes. There's just too many changes. This issue is about one small point you raised, which you appear to have solved in your branch. However, you have also made a number of other big changes that are not directly related to this issue.

I'm not against some of the design changes. I don't see why we can't work towards getting them into this project. However, I want to take this a little more slowly than just pulling in all your changes at once. I think the best approach will be for me to cherry pick some of what you have done and incorporate it into the master updating the tests as I go. I'll be able to better understand the changes and ensure it keeps with my vision for the project

**Comment by IsaacSanch** [comment]
@johncmckim That's correct... I have not yet had the opportunity to update the test cases

> However, you have also made a number of other big changes that are not directly related to this issue.

Correct, many of the other changes are related to the use case I have for HAL.

> The attributes support is interesting. However, does this change remove support for objects without attributes?

No. It fully supports the old methodology where an object which has not been decorated with attributes can be provided and embeds and links are declared separately. The attributes are just shortcuts to accomplish the same thing.

`GetFlattenedModelList` isn't actually a client function... its used internally to take all the embedded document tree, flatten it, and perform the same action across all of them. I use it at several points to assign the base URI.

The `expand` request parameter changes the response, as you assumed. This is one of my use case specific changes. I need to be able to return either embeds or present them as links depending on the call made to the API endpoint. Using an "expand" parameter that contains a comma-separated list of the values to embed was what made sense to me for this use case.

There's a decent amount of the recently added logic that can be stripped if either attributes or the expand parameter are undesirable for your feature set.

In the mean time I'm going to assume the need to rename my own project and treat it as a permanent fork. Some of the additional features I've implemented are ones I need to have long term for some APIs that are in the process of being developed.

**Comment by johncmckim** [comment]
@IsaacSanch  yes, the best approach will be for you to continue your fork under a different name. 

I've added support for JSON.NET attributes and added another issue for HAL attributes on models. I do like that idea.

Even though the work you did didn't get merged in, thanks for you work on this. It's always nice to have more ideas and input into a project.
