### ISSUE TITLE
Add Attribute support for models

### ISSUE THREAD

**Issue by johncmckim** [visualeyes/halcyon#6]
Add the ability to create a HAL Response from a model using attributes. Something similar to the following:

    [HalModel("~/api/")] // Link base & force hal settings
    [HalLink("self", "orders/{value}")] // add links to class
    [HalLink("users", "users/{value}")]
    public class OrderDto {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }

        public DateTime MadeDate { get; set; }
        public DateTime FulfilledDate { get; set; }

        // mark certain items as embedded - possibly support links here
        [HalEmbedded("items"), HalLink("orders/{orderid}/items/{id}")]
        public IEnumerable<OrderItemDto> Items { get; set; }
    }

The user should then be able to return the model using

    [HttpGet, Route("orders/{Id:guid}")]
    public IHttpActionResult GetOrder(Guid Id) {
       return this.Ok(new OrderDto());
    }

This would then be automatically serialised into HAL based on the accept type.

**Comment by johncmckim** [comment]
Based on discussion in #3

**Comment by NiklasArbin** [comment]
Going to submit a pull request for this hopefully today. I will start by adding the support for Web.Api

**Comment by johncmckim** [comment]
Ok thanks. I'm on holidays until the 20th, I'll review it when I'm back.

**Comment by NiklasArbin** [comment]
Ok, then we'll test this a bit more in our setup before doing a PR. If you're bored during your vacation you can have a look at my fork https://github.com/visualeyes/halcyon/compare/master...NiklasArbin:issue-6?expand=1

Basically the attributes are just markers that are used when creating the HALResponse. The JsonHALMediaTypeFormatter have been modify to detect the presense of the HalModelAttribute and then automatically creates a HALResponse based on the attribute-marked model.

Not sure if i'll add Link support to properties yet since there are some issues to address then.

Also performance wise there is still work to be done, by caching the reflected properties but it should not be an issue for very large result sets and can probably be done as a separate PR.

**Comment by johncmckim** [comment]
Closing this issue. Release pending.
